name: SignEdit
version: 1.5
description: Ever made a mistake on a sign, and not wanted to take the sign down to fix it? Now you don't have to!
author: Timr
website: http://dev.timroden.net/
main: net.timroden.signedit.SignEdit
database: false

commands:
    signedit:
        description: Allows you to edit a sign
        permission: signedit.edit

permissions:
    signedit.edit:
        description: Allows you to use /signedit
        
    signedit.override:
        description: Allows users to override LWC's protections.
        children:
            signedit.edit: true
            signedit.notify: true
        default: op
    signedit.notify:
        description: Notifys anyone with this permission when a signedit event happens
        children: 
            signedit.edit: true
        default: op