name: SignEdit
version: 1.5.2a
description: Ever made a mistake on a sign, and not wanted to take the sign down to fix it? Now you don't have to!
author: Timr, ThundrRok
website: http://dev.timroden.net/
main: net.timroden.signedit.SignEdit
database: false

commands:
    signedit:
        description: Allows you to edit a sign
        permission: signedit.edit
permissions:
    signedit.edit:
        description: Allows you to use /signedit
        default: false       
    signedit.override:
        description: Allows users to override LWC's protections.
        default: op
        children:
            signedit.edit: true
            signedit.notify: true       
    signedit.notify:
        description: Notifies anyone with this permission when a sign edit event happens
        default: false       
        children: 
            signedit.edit: true      