name: SignEdit
version: 1.1
description: Ever made a mistake on a sign, and not wanted to take the sign down to fix it? Now you don't have to!
author: Timr
website: http://dev.timroden.net/
main: net.timroden.signedit.SignEdit
database: false

commands:
    signedit:
        description: Edit a line on a sign
        permission: signedit.edit

permissions:
    signedit.edit:
        description: Allows you to use /signedit
        
    signedit.override:
        description: Allows users to override LWC's protections.
        children:
            signedit.edit: true
        default: op